### ISSUE TITLE
FEAT: Add navigation bar, Add new logo

### ISSUE THREAD

**Issue by world2222** [world2222/Stylish#1]
# Description
* Add a new logo for the app.
* Make a navigation bar that allows the user to navigate to multiple pages like home, create, search, and profile screen.

# Todo
- [x] Make a new logo and set as the app icon
- [x] Make a navigation bar
- [x] Set the screens that belongs to each navigation bar items
