### ISSUE TITLE
FEAT: Create wish list in MyPageScreen

### ISSUE THREAD

**Issue by world2222** [world2222/Stylish#11]
# Descriptions
Implement the wish list function in MyPageScreen.
<br>

# Todo
- [x] Put bookmark icon on each DetailScreen.
- [x] Change the shape of the bookmark depending on whether it's in the database or not.
- [x] Style MyPageScreen. Make two screens, one for when there's no data in database and another for when there is.
