### ISSUE TITLE
FEAT: Show items on HomeScreen

### ISSUE THREAD

**Issue by world2222** [world2222/Stylish#6]
# Description
* Show items on HomeScreen with name, price and image.
<br>

# Todo
- [x] Setup proper api
- [x] Implement viewmodels for HomeScreen or SharedScreen
- [x] Showing info of the items on HomeScreen
